import re
from datetime import datetime
from io import BytesIO
from typing import List, Optional
from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, PageBreak, Table, TableStyle
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.pdfgen import canvas

class NumberedCanvas(canvas.Canvas):
    """
    Two-pass canvas renderer to dynamically calculate total page count 
    and draw a running footer on all pages.
    """
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._saved_page_states = []

    def showPage(self):
        self._saved_page_states.append(dict(self.__dict__))
        self._startPage()

    def save(self):
        num_pages = len(self._saved_page_states)
        for state in self._saved_page_states:
            self.__dict__.update(state)
            self.draw_footer(num_pages)
            super().showPage()
        super().save()

    def draw_footer(self, page_count: int):
        self.saveState()
        self.setFont("Helvetica", 9)
        self.setFillColor(colors.HexColor("#6B7280"))
        
        # Horizontal line above footer
        self.setStrokeColor(colors.HexColor("#E5E7EB"))
        self.setLineWidth(0.5)
        self.line(54, 50, self._pagesize[0] - 54, 50)
        
        # Footer branding & pagination
        self.drawString(54, 35, "Generated by AI Assistant")
        page_str = f"Page {self._pageNumber} of {page_count}"
        self.drawRightString(self._pagesize[0] - 54, 35, page_str)
        self.restoreState()


def parse_inline_markdown(text: str) -> str:
    """
    Escape XML special characters to prevent ReportLab markup parsing errors,
    and convert standard markdown bold (**) and italic (*) to ReportLab-compatible HTML tags.
    """
    if not text:
        return ""
    # XML escape & first, then < and >
    text = text.replace('&', '&amp;').replace('<', '&lt;').replace('>', '&gt;')
    
    # Convert bold (supports ** and __)
    text = re.sub(r'\*\*(.*?)\*\*|__(.*?)__', r'<b>\1\2</b>', text)
    
    # Convert italics (supports * and _)
    text = re.sub(r'\*(.*?)\*|_(.*?)_', r'<i>\1\2</i>', text)
    
    return text


def markdown_to_flowables(text: str, styles) -> list:
    """
    Parse a multi-line markdown block and construct list of ReportLab Flowables.
    Supports headings (#, ##, ###), bullets (- /*), blockquotes (>), and normal paragraphs.
    """
    flowables = []
    lines = text.split('\n')
    
    body_style = ParagraphStyle(
        'PDFBody',
        parent=styles['Normal'],
        fontName='Helvetica',
        fontSize=10,
        leading=14,
        textColor=colors.HexColor("#1F2937"),
        spaceAfter=6
    )
    
    h1_style = ParagraphStyle(
        'PDFH1',
        parent=styles['Heading1'],
        fontName='Helvetica-Bold',
        fontSize=14,
        leading=18,
        textColor=colors.HexColor("#1E3A8A"),
        spaceBefore=12,
        spaceAfter=6,
        keepWithNext=True
    )
    
    h2_style = ParagraphStyle(
        'PDFH2',
        parent=styles['Heading2'],
        fontName='Helvetica-Bold',
        fontSize=12,
        leading=16,
        textColor=colors.HexColor("#2563EB"),
        spaceBefore=10,
        spaceAfter=4,
        keepWithNext=True
    )
    
    h3_style = ParagraphStyle(
        'PDFH3',
        parent=styles['Heading3'],
        fontName='Helvetica-Bold',
        fontSize=11,
        leading=15,
        textColor=colors.HexColor("#1E40AF"),
        spaceBefore=8,
        spaceAfter=4,
        keepWithNext=True
    )
    
    bullet_style = ParagraphStyle(
        'PDFBullet',
        parent=body_style,
        leftIndent=15,
        firstLineIndent=-10,
        spaceAfter=4
    )
    
    block_quote_style = ParagraphStyle(
        'PDFBlockQuote',
        parent=body_style,
        leftIndent=20,
        textColor=colors.HexColor("#4B5563"),
        backColor=colors.HexColor("#F9FAFB"),
        borderColor=colors.HexColor("#E5E7EB"),
        borderWidth=0.5,
        borderPadding=6,
        spaceAfter=6
    )

    in_list = False
    
    for line in lines:
        stripped = line.strip()
        if not stripped:
            if in_list:
                in_list = False
            continue
            
        if stripped.startswith('# '):
            flowables.append(Paragraph(parse_inline_markdown(stripped[2:]), h1_style))
        elif stripped.startswith('## '):
            flowables.append(Paragraph(parse_inline_markdown(stripped[3:]), h2_style))
        elif stripped.startswith('### '):
            flowables.append(Paragraph(parse_inline_markdown(stripped[4:]), h3_style))
        elif stripped.startswith('- ') or stripped.startswith('* ') or stripped.startswith('• '):
            in_list = True
            flowables.append(Paragraph(f"&bull; {parse_inline_markdown(stripped[2:])}", bullet_style))
        elif re.match(r'^\d+\.\s+', stripped):
            in_list = True
            match = re.match(r'^(\d+)\.\s+(.*)', stripped)
            num = match.group(1)
            content = match.group(2)
            flowables.append(Paragraph(f"{num}. {parse_inline_markdown(content)}", bullet_style))
        elif stripped.startswith('>'):
            content = stripped[1:].strip()
            flowables.append(Paragraph(parse_inline_markdown(content), block_quote_style))
        else:
            flowables.append(Paragraph(parse_inline_markdown(stripped), body_style))
            
    return flowables


def get_hr(color=colors.HexColor("#E5E7EB"), thickness=0.5, space_before=5, space_after=15):
    """
    Construct a responsive horizontal divider line using ReportLab Table flowables.
    """
    t = Table([['']], colWidths=['100%'])
    t.setStyle(TableStyle([
        ('LINEBELOW', (0,0), (-1,-1), thickness, color),
        ('BOTTOMPADDING', (0,0), (-1,-1), 0),
        ('TOPPADDING', (0,0), (-1,-1), 0),
    ]))
    t.spaceBefore = space_before
    t.spaceAfter = space_after
    return t


def generate_pdf(title: str, summary: Optional[str] = None, chat_history: Optional[List[dict]] = None) -> bytes:
    """
    Generate a styled A4 PDF document containing AI summaries, Q&A transcripts, or both.
    """
    buffer = BytesIO()
    
    # Initialize page document with 0.75-inch (54 points) margins
    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        leftMargin=54,
        rightMargin=54,
        topMargin=54,
        bottomMargin=64
    )
    
    styles = getSampleStyleSheet()
    
    # Document header typography
    title_style = ParagraphStyle(
        'DocTitle',
        parent=styles['Title'],
        fontName='Helvetica-Bold',
        fontSize=22,
        leading=26,
        textColor=colors.HexColor("#1E3A8A"), # Brand dark blue
        alignment=0, # Left aligned
        spaceAfter=4
    )
    
    subtitle_style = ParagraphStyle(
        'DocSubtitle',
        parent=styles['Normal'],
        fontName='Helvetica',
        fontSize=9,
        leading=13,
        textColor=colors.HexColor("#4B5563"),
        spaceAfter=15
    )
    
    section_title_style = ParagraphStyle(
        'SectionTitle',
        parent=styles['Heading1'],
        fontName='Helvetica-Bold',
        fontSize=15,
        leading=19,
        textColor=colors.HexColor("#1E3A8A"),
        spaceBefore=14,
        spaceAfter=8,
        keepWithNext=True
    )
    
    story = []
    
    # 1. Main Document Header (Title + Metadata + divider)
    story.append(Paragraph(title, title_style))
    
    timestamp_str = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    story.append(Paragraph(f"Generated on {timestamp_str} | LegalEase AI Assistant", subtitle_style))
    story.append(get_hr(color=colors.HexColor("#2563EB"), thickness=1.5, space_after=15))
    
    # 2. Document Summary Section
    if summary and summary.strip():
        story.append(Paragraph("AI Document Summary", section_title_style))
        story.append(get_hr(color=colors.HexColor("#D1D5DB"), thickness=0.5, space_after=10))
        
        summary_flowables = markdown_to_flowables(summary, styles)
        story.extend(summary_flowables)
        
    # Page break if both sections are present
    if summary and summary.strip() and chat_history and len(chat_history) > 0:
        story.append(PageBreak())
        
    # 3. Chat History Transcript Section
    if chat_history and len(chat_history) > 0:
        story.append(Paragraph("AI Chat & Q&A History", section_title_style))
        story.append(get_hr(color=colors.HexColor("#D1D5DB"), thickness=0.5, space_after=10))
        
        role_user_style = ParagraphStyle(
            'RoleUser',
            parent=styles['Normal'],
            fontName='Helvetica-Bold',
            fontSize=10,
            leading=14,
            textColor=colors.HexColor("#2563EB"), # User blue
            spaceBefore=8,
            spaceAfter=4,
            keepWithNext=True
        )
        
        role_assistant_style = ParagraphStyle(
            'RoleAssistant',
            parent=styles['Normal'],
            fontName='Helvetica-Bold',
            fontSize=10,
            leading=14,
            textColor=colors.HexColor("#059669"), # Assistant green
            spaceBefore=8,
            spaceAfter=4,
            keepWithNext=True
        )
        
        for msg in chat_history:
            role = msg.get("role", "user")
            content = msg.get("content", "")
            
            # Map role header
            if role in ("user",):
                story.append(Paragraph("User:", role_user_style))
            else:
                story.append(Paragraph("AI Assistant:", role_assistant_style))
                
            # Render message bubble content
            content_flowables = markdown_to_flowables(content, styles)
            story.extend(content_flowables)
            story.append(Spacer(1, 6))
            
    # Build Document PDF using the Dynamic Page numbering canvas
    doc.build(story, canvasmaker=NumberedCanvas)
    
    pdf_bytes = buffer.getvalue()
    buffer.close()
    return pdf_bytes
